version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
  nadine:
    build:
      context: .
      dockerfile: Dockerfile-nadine
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
